    <div class="nationTree" id="ntree-china" style="display: none;">
        <div class="treeWrapper">
            <div class="levelLine" style="left:0px;"></div>
            <div class="levelLine" style="left:324px;"></div>
            <div class="levelLine" style="left:648px;"></div>
            <div class="levelLine" style="left:972px;"></div>
            <div class="levelLine" style="left:1296px;"></div>
            <div id="levels">
                <div>I</div>
                <div>II</div>
                <div>III</div>
                <div>IV</div>
                <div>V</div>
                <div>VI</div>
                <div>VII</div>
                <div>VIII</div>
                <div>IX</div>
                <div>X</div>
            </div>
            <div id="tree">
                <div class="tblock column1 row5"><a href="tank/Ch06_Renault_NC31" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/china-ch06_renault_nc31.png"></div><span class="mark" title="Renault NC-31">NC-31</span><span class="level">I</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
                <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class1.png" alt=""></span><div class="gamerstats" style="z-index:190;">2 боёв<br/>1 побед<br/>50,00 %</div><div class="gamerbattles" style="z-index:191;">2</div></div>
                <div class="tblock column2 row5"><a href="tank/Ch07_Vickers_MkE_Type_BT26" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/china-ch07_vickers_mke_type_bt26.png"></div><span class="mark" title="Vickers Mk. E Type B">VAE Type B</span><span class="level">II</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
                <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
                <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class2.png" alt=""></span><div class="gamerstats" style="z-index:190;">5 боёв<br/>4 побед<br/>80,00 %</div><div class="gamerbattles" style="z-index:191;">5</div></div>
                <div class="tblock column3 row5"><a href="tank/Ch08_Type97_Chi_Ha" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/china-ch08_type97_chi_ha.png"></div><span class="mark" title="Type 2597 Chi-Ha">Chi-Ha</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
                <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
                <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class1.png" alt=""></span><div class="gamerstats" style="z-index:190;">8 боёв<br/>4 побед<br/>50,00 %</div><div class="gamerbattles" style="z-index:191;">8</div></div>
                <div class="tblock column4 row5"><a href="tank/Ch09_M5" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/china-ch09_m5.png"></div><span class="mark" title="M5A1 Stuart">M5A1 Stuart</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
                <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
                <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class3.png" alt=""></span><div class="gamerstats" style="z-index:190;">49 боёв<br/>29 побед<br/>59,18 %</div><div class="gamerbattles" style="z-index:191;">49</div></div>
                <div class="tblock column5 row5"><a href="tank/Ch21_T34" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/china-ch21_t34.png"></div><span class="mark" title="Type T-34">Type T-34</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
                <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
                <img class="lineRU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
                <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
                <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:190;">81 боёв<br/>42 побед<br/>51,85 %</div><div class="gamerbattles" style="z-index:191;">81</div></div>
                <div class="tblock column6 row4"><a href="tank/Ch15_59_16" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/china-ch15_59_16.png"></div><span class="mark" title="59-16">59-16</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
                <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
                <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
                <div class="tblock column6 row5"><a href="tank/Ch20_Type58" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/china-ch20_type58.png"></div><span class="mark" title="Type 58">Type 58</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
                <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
                <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
                <img class="lineRD" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
                <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class3.png" alt=""></span><div class="gamerstats" style="z-index:190;">115 боёв<br/>73 побед<br/>63,48 %</div><div class="gamerbattles" style="z-index:191;">115</div></div>
                <div class="tblock column6 row7"><a href="tank/Ch24_Type64" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/china-ch24_type64.png"></div><span class="mark" title="Type 64">Type 64</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="3500" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
                <div class="tblock column7 row4"><a href="tank/Ch16_WZ_131" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/china-ch16_wz_131.png"></div><span class="mark" title="WZ-131">WZ-131</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
                <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
                <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
                <div class="tblock column7 row5"><a href="tank/Ch04_T34_1" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/china-ch04_t34_1.png"></div><span class="mark" title="T-34-1">T-34-1</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
                <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
                <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
                <div class="tblock column7 row6"><a href="tank/Ch10_IS2" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/china-ch10_is2.png"></div><span class="mark" title="IS-2">IS-2</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
                <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
                <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class3.png" alt=""></span><div class="gamerstats" style="z-index:188;">25 боёв<br/>11 побед<br/>44,00 %</div><div class="gamerbattles" style="z-index:189;">25</div></div>
                <div class="tblock column8 row4"><a href="tank/Ch17_WZ131_1_WZ132" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/china-ch17_wz131_1_wz132.png"></div><span class="mark" title="WZ-132">WZ-132</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
                <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
                <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
                <div class="tblock column8 row5"><a href="tank/Ch05_T34_2" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/china-ch05_t34_2.png"></div><span class="mark" title="T-34-2">T-34-2</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
                <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
                <img class="lineRU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
                <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
                <div class="tblock column8 row6"><a href="tank/Ch11_110" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/china-ch11_110.png"></div><span class="mark" title="110">110</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
                <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
                <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
                <div class="tblock column8 row7"><a href="tank/Ch23_112" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/china-ch23_112.png"></div><span class="mark" title="112">112</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="12250" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
                <div class="tblock column8 row8"><a href="tank/Ch14_T34_3" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/china-ch14_t34_3.png"></div><span class="mark" title="T-34-3">T-34-3</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="11000" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
                <div class="tblock column9 row4"><a href="tank/Ch18_WZ-120" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/china-ch18_wz-120.png"></div><span class="mark" title="WZ-120">WZ-120</span><span class="level">IX</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
                <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
                <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
                <div class="tblock column9 row6"><a href="tank/Ch12_111_1_2_3" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/china-ch12_111_1_2_3.png"></div><span class="mark" title="WZ-111 model 1-4">WZ-111 1-4</span><span class="level">IX</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
                <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
                <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
                <div class="tblock column10 row4"><a href="tank/Ch19_121" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/china-ch19_121.png"></div><span class="mark" title="121">121</span><span class="level">X</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
                <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
                <div class="tblock column10 row6"><a href="tank/Ch22_113" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/china-ch22_113.png"></div><span class="mark" title="113">113</span><span class="level">X</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
                <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
            </div>
        </div>
    </div>