<div class="nationTree" id="ntree-france" style="display: none;">
    <div class="treeWrapper"><div class="levelLine" style="left:0px;"></div>
    <div class="levelLine" style="left:324px;"></div>
    <div class="levelLine" style="left:648px;"></div>
    <div class="levelLine" style="left:972px;"></div>
    <div class="levelLine" style="left:1296px;"></div>
    <div id="levels"><div>I</div>
    <div>II</div>
    <div>III</div>
    <div>IV</div>
    <div>V</div>
    <div>VI</div>
    <div>VII</div>
    <div>VIII</div>
    <div>IX</div>
    <div>X</div>
    </div>
    <div id="tree">
    <div class="tblock column1 row5"><a href="tank/RenaultFT" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-renaultft.png"></div><span class="mark" title="Renault FT">FT</span><span class="level">I</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <img class="lineRU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="216" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <img class="lineRU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <img class="lineRD" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <img class="lineRD" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="270" alt="">
    <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class1.png" alt=""></span><div class="gamerstats" style="z-index:190;">1 боёв<br/>1 побед<br/>100,00 %</div><div class="gamerbattles" style="z-index:191;">1</div></div>
    <div class="tblock column2 row1"><a href="tank/RenaultFT_AC" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-renaultft_ac.png"></div><span class="mark" title="Renault FT AC">FT AC</span><span class="level">II</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class3.png" alt=""></span><div class="gamerstats" style="z-index:198;">3 боёв<br/>2 побед<br/>66,67 %</div><div class="gamerbattles" style="z-index:199;">3</div></div>
    <div class="tblock column2 row4"><a href="tank/D1" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-d1.png"></div><span class="mark" title="D1">D1</span><span class="level">II</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class1.png" alt=""></span><div class="gamerstats" style="z-index:192;">5 боёв<br/>2 побед<br/>40,00 %</div><div class="gamerbattles" style="z-index:193;">5</div></div>
    <div class="tblock column2 row6"><a href="tank/Hotchkiss_H35" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-hotchkiss_h35.png"></div><span class="mark" title="Hotchkiss H35">H35</span><span class="level">II</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class1.png" alt=""></span><div class="gamerstats" style="z-index:188;">1 боёв<br/>1 побед<br/>100,00 %</div><div class="gamerbattles" style="z-index:189;">1</div></div>
    <div class="tblock column2 row10"><a href="tank/RenaultBS" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-renaultbs.png"></div><span class="mark" title="Renault FT 75 BS">FT BS</span><span class="level">II</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column3 row1"><a href="tank/RenaultUE57" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-renaultue57.png"></div><span class="mark" title="Renault UE 57">UE 57</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column3 row2"><a href="tank/FCM_36Pak40" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-fcm_36pak40.png"></div><span class="mark" title="FCM 36 Pak 40">FCM36Pak40</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="850" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column3 row4"><a href="tank/D2" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-d2.png"></div><span class="mark" title="D2">D2</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class3.png" alt=""></span><div class="gamerstats" style="z-index:192;">17 боёв<br/>11 побед<br/>64,71 %</div><div class="gamerbattles" style="z-index:193;">17</div></div>
    <div class="tblock column3 row6"><a href="tank/AMX38" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-amx38.png"></div><span class="mark" title="AMX 38">AMX 38</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class2.png" alt=""></span><div class="gamerstats" style="z-index:188;">28 боёв<br/>10 побед<br/>35,71 %</div><div class="gamerbattles" style="z-index:189;">28</div></div>
    <div class="tblock column3 row10"><a href="tank/Lorraine39_L_AM" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-lorraine39_l_am.png"></div><span class="mark" title="Lorraine 39L AM">Lorr. 39L AM</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column4 row1"><a href="tank/Somua_Sau_40" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-somua_sau_40.png"></div><span class="mark" title="Somua SAu 40">SAu 40</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column4 row4"><a href="tank/B1" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-b1.png"></div><span class="mark" title="B1">B1</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class2.png" alt=""></span><div class="gamerstats" style="z-index:192;">13 боёв<br/>4 побед<br/>30,77 %</div><div class="gamerbattles" style="z-index:193;">13</div></div>
    <div class="tblock column4 row6"><a href="tank/AMX40" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-amx40.png"></div><span class="mark" title="AMX 40">AMX 40</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class1.png" alt=""></span><div class="gamerstats" style="z-index:188;">18 боёв<br/>8 побед<br/>44,44 %</div><div class="gamerbattles" style="z-index:189;">18</div></div>
    <div class="tblock column4 row10"><a href="tank/AMX_Ob_Am105" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-amx_ob_am105.png"></div><span class="mark" title="AMX 105 AM mle. 47">AMX 105 AM</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column5 row1"><a href="tank/S_35CA" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-s_35ca.png"></div><span class="mark" title="S35 CA">S35 CA</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column5 row4"><a href="tank/BDR_G1B" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-bdr_g1b.png"></div><span class="mark" title="BDR G1 B">BDR G1 B</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class3.png" alt=""></span><div class="gamerstats" style="z-index:192;">54 боёв<br/>36 побед<br/>66,67 %</div><div class="gamerbattles" style="z-index:193;">54</div></div>
    <div class="tblock column5 row6"><a href="tank/ELC_AMX" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-elc_amx.png"></div><span class="mark" title="ELC AMX">ELC AMX</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:188;">134 боёв<br/>63 побед<br/>47,01 %</div><div class="gamerbattles" style="z-index:189;">134</div></div>
    <div class="tblock column5 row9"><a href="tank/_105_leFH18B2" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-_105_lefh18b2.png"></div><span class="mark" title="105 leFH18B2">leFH18B2</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="1500" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column5 row10"><a href="tank/AMX_105AM" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-amx_105am.png"></div><span class="mark" title="AMX 13 105 AM mle. 50">AMX 13 AM</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column6 row1"><a href="tank/ARL_V39" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-arl_v39.png"></div><span class="mark" title="ARL V39">ARL V39</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column6 row4"><a href="tank/ARL_44" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-arl_44.png"></div><span class="mark" title="ARL 44">ARL 44</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:192;">143 боёв<br/>88 побед<br/>61,54 %</div><div class="gamerbattles" style="z-index:193;">143</div></div>
    <div class="tblock column6 row6"><a href="tank/AMX_12t" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-amx_12t.png"></div><span class="mark" title="AMX 12 t">AMX 12 t</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <img class="lineD" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="216" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column6 row10"><a href="tank/AMX_13F3AM" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-amx_13f3am.png"></div><span class="mark" title="AMX 13 F3 AM">AMX 13 F3</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="arrTB" src="http://armor.kiev.ua/wot/images/arrow/t_b8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column7 row1"><a href="tank/AMX_AC_Mle1946" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-amx_ac_mle1946.png"></div><span class="mark" title="AMX AC mle. 46">AMX AC 46</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column7 row4"><a href="tank/AMX_M4_1945" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-amx_m4_1945.png"></div><span class="mark" title="AMX M4 mle. 45">AMX M4 45</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class2.png" alt=""></span><div class="gamerstats" style="z-index:192;">40 боёв<br/>28 побед<br/>70,00 %</div><div class="gamerbattles" style="z-index:193;">40</div></div>
    <div class="tblock column7 row6"><a href="tank/AMX_13_75" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-amx_13_75.png"></div><span class="mark" title="AMX 13 75">AMX 13 75</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column7 row10"><a href="tank/Lorraine155_50" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-lorraine155_50.png"></div><span class="mark" title="Lorraine 155 mle. 50">Lorr. 155 50</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column8 row1"><a href="tank/AMX_AC_Mle1948" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-amx_ac_mle1948.png"></div><span class="mark" title="AMX AC mle. 48">AMX AC 48</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column8 row4"><a href="tank/AMX_50_100" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-amx_50_100.png"></div><span class="mark" title="AMX 50 100">AMX 50 100</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class3.png" alt=""></span><div class="gamerstats" style="z-index:192;">151 боёв<br/>99 побед<br/>65,56 %</div><div class="gamerbattles" style="z-index:193;">151</div></div>
    <div class="tblock column8 row6"><a href="tank/AMX_13_90" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-amx_13_90.png"></div><span class="mark" title="AMX 13 90">AMX 13 90</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column8 row5"><a href="tank/FCM_50t" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-fcm_50t.png"></div><span class="mark" title="FCM 50 t">FCM 50 t</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="11900" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column8 row10"><a href="tank/Lorraine155_51" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-lorraine155_51.png"></div><span class="mark" title="Lorraine 155 mle. 51">Lorr. 155 51</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column9 row1"><a href="tank/AMX50_Foch" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-amx50_foch.png"></div><span class="mark" title="AMX 50 Foch">Foch</span><span class="level">IX</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column9 row4"><a href="tank/AMX_50_120" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-amx_50_120.png"></div><span class="mark" title="AMX 50 120">AMX 50 120</span><span class="level">IX</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column9 row6"><a href="tank/Lorraine40t" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-lorraine40t.png"></div><span class="mark" title="Lorraine 40 t">Lorr. 40 t</span><span class="level">IX</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column9 row10"><a href="tank/Bat_Chatillon155_55" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-bat_chatillon155_55.png"></div><span class="mark" title="Bat.-Châtillon 155 55">B-C 155 55</span><span class="level">IX</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column10 row1"><a href="tank/AMX_50Fosh_155" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-amx_50fosh_155.png"></div><span class="mark" title="AMX 50 Foch (155)">Foch 155</span><span class="level">X</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column10 row4"><a href="tank/F10_AMX_50B" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-f10_amx_50b.png"></div><span class="mark" title="AMX 50 B">AMX 50 B</span><span class="level">X</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column10 row6"><a href="tank/Bat_Chatillon25t" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-bat_chatillon25t.png"></div><span class="mark" title="Bat.-Châtillon 25 t">B-C 25 t</span><span class="level">X</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column10 row10"><a href="tank/Bat_Chatillon155_58" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/france-bat_chatillon155_58.png"></div><span class="mark" title="Bat.-Châtillon 155 58">B-C 155 58</span><span class="level">X</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    </div>
    </div>
    </div>