<div class="nationTree" id="ntree-germany" style="display: none;">
<div class="treeWrapper"><div class="levelLine" style="left:0px;"></div>
<div class="levelLine" style="left:324px;"></div>
<div class="levelLine" style="left:648px;"></div>
<div class="levelLine" style="left:972px;"></div>
<div class="levelLine" style="left:1296px;"></div>
<div id="levels"><div>I</div>
<div>II</div>
<div>III</div>
<div>IV</div>
<div>V</div>
<div>VI</div>
<div>VII</div>
<div>VIII</div>
<div>IX</div>
<div>X</div>
</div>
  <div id="tree">
  <div class="tblock column1 row5"><a href="tank/Ltraktor" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-ltraktor.png"></div><span class="mark" title="Leichttraktor">L.Tr.</span><span class="level">I</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="108" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRD" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRD" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="162" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="216" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRD" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="324" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class2.png" alt=""></span><div class="gamerstats" style="z-index:190;">8 боёв<br/>5 побед<br/>62,50 %</div><div class="gamerbattles" style="z-index:191;">8</div></div>
<div class="tblock column2 row1"><a href="tank/GW_Mk_VIe" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-gw_mk_vie.png"></div><span class="mark" title="G.Pz. Mk. VI (e)">G.Pz. Mk. VI</span><span class="level">II</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRD" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column2 row3"><a href="tank/PanzerJager_I" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-panzerjager_i.png"></div><span class="mark" title="Panzerjäger I">Pz.Jäg. I</span><span class="level">II</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class2.png" alt=""></span><div class="gamerstats" style="z-index:194;">16 боёв<br/>12 побед<br/>75,00 %</div><div class="gamerbattles" style="z-index:195;">16</div></div>
<div class="tblock column2 row6"><a href="tank/Pz35t" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-pz35t.png"></div><span class="mark" title="Pz.Kpfw. 35 (t)">Pz. 35 (t)</span><span class="level">II</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class3.png" alt=""></span><div class="gamerstats" style="z-index:188;">21 боёв<br/>10 побед<br/>47,62 %</div><div class="gamerbattles" style="z-index:189;">21</div></div>
<div class="tblock column2 row8"><a href="tank/PzII" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-pzii.png"></div><span class="mark" title="Pz.Kpfw. II">Pz. II</span><span class="level">II</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRD" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="108" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:184;">10 боёв<br/>6 побед<br/>60,00 %</div><div class="gamerbattles" style="z-index:185;">10</div></div>
<div class="tblock column2 row11"><a href="tank/PzI" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-pzi.png"></div><span class="mark" title="Pz.Kpfw. I">Pz. I</span><span class="level">II</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class1.png" alt=""></span><div class="gamerstats" style="z-index:178;">6 боёв<br/>2 побед<br/>33,33 %</div><div class="gamerbattles" style="z-index:179;">6</div></div>
<div class="tblock column3 row2"><a href="tank/Bison_I" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-bison_i.png"></div><span class="mark" title="Sturmpanzer I Bison">Bison</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column3 row1"><a href="tank/Wespe" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-wespe.png"></div><span class="mark" title="Wespe">Wespe</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column3 row3"><a href="tank/G20_Marder_II" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-g20_marder_ii.png"></div><span class="mark" title="Marder II">Marder II</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRD" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="108" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class3.png" alt=""></span><div class="gamerstats" style="z-index:194;">60 боёв<br/>31 побед<br/>51,67 %</div><div class="gamerbattles" style="z-index:195;">60</div></div>
<div class="tblock column3 row6"><a href="tank/Pz38t" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-pz38t.png"></div><span class="mark" title="Pz.Kpfw. 38 (t)">Pz. 38 (t)</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column3 row7"><a href="tank/Pz_IV_AusfA" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-pz_iv_ausfa.png"></div><span class="mark" title="Pz.Kpfw. IV Ausf. A">Pz. IV A</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrBT" src="http://armor.kiev.ua/wot/images/arrow/b_t8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column4 row7"><a href="tank/Pz_IV_AusfD" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-pz_iv_ausfd.png"></div><span class="mark" title="Pz.Kpfw. IV Ausf. D">Pz. IV D</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column3 row5"><a href="tank/T-15" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-t-15.png"></div><span class="mark" title="T-15">T-15</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="900" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column3 row4"><a href="tank/S35_captured" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-s35_captured.png"></div><span class="mark" title="Pz.Kpfw. S35 739 (f)">Pz. S35</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="1000" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column3 row8"><a href="tank/PzIII_A" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-pziii_a.png"></div><span class="mark" title="Pz.Kpfw. III Ausf. A">Pz. III A</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="lineU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRD" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:184;">8 боёв<br/>6 побед<br/>75,00 %</div><div class="gamerbattles" style="z-index:185;">8</div></div>
<div class="tblock column3 row10"><a href="tank/Pz_II_AusfG" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-pz_ii_ausfg.png"></div><span class="mark" title="Pz.Kpfw. II Ausf. G">Pz. II G</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column3 row11"><a href="tank/PzI_ausf_C" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-pzi_ausf_c.png"></div><span class="mark" title="Pz.Kpfw. I Ausf. C">Pz. I C</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column4 row1"><a href="tank/Pz_Sfl_IVb" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-pz_sfl_ivb.png"></div><span class="mark" title="Pz.Sfl. IVb">Pz.Sfl. IVb</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column4 row2"><a href="tank/Sturmpanzer_II" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-sturmpanzer_ii.png"></div><span class="mark" title="Sturmpanzer II">St.Pz. II</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="arrLRU" src="http://armor.kiev.ua/wot/images/arrow/lb_rt8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:196;">37 боёв<br/>16 побед<br/>43,24 %</div><div class="gamerbattles" style="z-index:197;">37</div></div>
<div class="tblock column4 row3"><a href="tank/Marder_III" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-marder_iii.png"></div><span class="mark" title="Marder 38T">Marder 38T</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="lineU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="-54" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class2.png" alt=""></span><div class="gamerstats" style="z-index:194;">34 боёв<br/>18 побед<br/>52,94 %</div><div class="gamerbattles" style="z-index:195;">34</div></div>
<div class="tblock column4 row4"><a href="tank/G101_StuG_III" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-g101_stug_iii.png"></div><span class="mark" title="StuG III Ausf. B">StuG III B</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrBT" src="http://armor.kiev.ua/wot/images/arrow/b_t8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column4 row5"><a href="tank/Hetzer" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-hetzer.png"></div><span class="mark" title="Hetzer">Hetzer</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="arrBT" src="http://armor.kiev.ua/wot/images/arrow/b_t8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="108" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:190;">267 боёв<br/>153 побед<br/>57,30 %</div><div class="gamerbattles" style="z-index:191;">267</div></div>
<div class="tblock column4 row6"><a href="tank/Pz38_NA" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-pz38_na.png"></div><span class="mark" title="Pz.Kpfw. 38 (t) n.A.">Pz. 38 nA</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="lineU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column4 row11"><a href="tank/PzII_Luchs" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-pzii_luchs.png"></div><span class="mark" title="Pz.Kpfw. II Luchs">Luchs</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLRD" src="http://armor.kiev.ua/wot/images/arrow/lt_rb8.png" alt="">
<img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column4 row8"><a href="tank/DW_II" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-dw_ii.png"></div><span class="mark" title="Durchbruchswagen 2">D.W. 2</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:184;">31 боёв<br/>18 побед<br/>58,06 %</div><div class="gamerbattles" style="z-index:185;">31</div></div>
<div class="tblock column4 row9"><a href="tank/PzIII_AusfJ" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-pziii_ausfj.png"></div><span class="mark" title="Pz.Kpfw. III">Pz. III</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column4 row10"><a href="tank/VK2001DB" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-vk2001db.png"></div><span class="mark" title="VK 20.01 (D)">VK 20.01 D</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column5 row1"><a href="tank/Grille" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-grille.png"></div><span class="mark" title="Grille">Grille</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class3.png" alt=""></span><div class="gamerstats" style="z-index:198;">65 боёв<br/>44 побед<br/>67,69 %</div><div class="gamerbattles" style="z-index:199;">65</div></div>
<div class="tblock column5 row2"><a href="tank/Pz_Sfl_IVc" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-pz_sfl_ivc.png"></div><span class="mark" title="Pz.Sfl. IVc">Pz.Sfl. IVc</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLRU" src="http://armor.kiev.ua/wot/images/arrow/lb_rt8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:196;">148 боёв<br/>87 побед<br/>58,78 %</div><div class="gamerbattles" style="z-index:197;">148</div></div>
<div class="tblock column5 row3"><a href="tank/StuG_40_AusfG" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-stug_40_ausfg.png"></div><span class="mark" title="StuG III Ausf. G">StuG III G</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:194;">114 боёв<br/>70 побед<br/>61,40 %</div><div class="gamerbattles" style="z-index:195;">114</div></div>
<div class="tblock column5 row6"><a href="tank/Pz_IV_AusfH" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-pz_iv_ausfh.png"></div><span class="mark" title="Pz.Kpfw. IV Ausf. H">Pz. IV H</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column5 row4"><a href="tank/T-25" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-t-25.png"></div><span class="mark" title="T-25">T-25</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="1500" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column5 row8"><a href="tank/PzIV_Hydro" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-pziv_hydro.png"></div><span class="mark" title="Pz.Kpfw. IV hydrostat.">Pz. IV hydr.</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="2500" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column5 row11"><a href="tank/VK1602" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-vk1602.png"></div><span class="mark" title="VK 16.02 Leopard">Leopard</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="108" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column5 row7"><a href="tank/VK3001H" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-vk3001h.png"></div><span class="mark" title="VK 30.01 (H)">VK 30.01 H</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLRU" src="http://armor.kiev.ua/wot/images/arrow/lb_rt8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:186;">86 боёв<br/>43 побед<br/>50,00 %</div><div class="gamerbattles" style="z-index:187;">86</div></div>
<div class="tblock column5 row9"><a href="tank/PzIII_IV" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-pziii_iv.png"></div><span class="mark" title="Pz.Kpfw. III/IV">Pz. III/IV</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column6 row1"><a href="tank/Hummel" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-hummel.png"></div><span class="mark" title="Hummel">Hummel</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class3.png" alt=""></span><div class="gamerstats" style="z-index:198;">48 боёв<br/>31 побед<br/>64,58 %</div><div class="gamerbattles" style="z-index:199;">48</div></div>
<div class="tblock column6 row2"><a href="tank/Nashorn" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-nashorn.png"></div><span class="mark" title="Nashorn">Nashorn</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:196;">87 боёв<br/>61 побед<br/>70,11 %</div><div class="gamerbattles" style="z-index:197;">87</div></div>
<div class="tblock column6 row3"><a href="tank/JagdPzIV" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-jagdpziv.png"></div><span class="mark" title="Jagdpanzer IV">Jg.Pz. IV</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:194;">47 боёв<br/>26 побед<br/>55,32 %</div><div class="gamerbattles" style="z-index:195;">47</div></div>
<div class="tblock column6 row4"><a href="tank/DickerMax" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-dickermax.png"></div><span class="mark" title="Dicker Max">Dicker Max</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="3200" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column6 row5"><a href="tank/VK3001P" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-vk3001p.png"></div><span class="mark" title="VK 30.01 (P)">VK 30.01 P</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column6 row6"><a href="tank/VK3601H" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-vk3601h.png"></div><span class="mark" title="VK 36.01 (H)">VK 36.01 H</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="arrLRU" src="http://armor.kiev.ua/wot/images/arrow/lb_rt8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class3.png" alt=""></span><div class="gamerstats" style="z-index:188;">34 боёв<br/>20 побед<br/>58,82 %</div><div class="gamerbattles" style="z-index:189;">34</div></div>
<div class="tblock column6 row7"><a href="tank/VK3002M" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-vk3002m.png"></div><span class="mark" title="VK 30.02 (M)">VK 30.02 M</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column6 row8"><a href="tank/VK3002DB_V1" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-vk3002db_v1.png"></div><span class="mark" title="VK 30.01 (D)">VK 30.01 D</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLRU" src="http://armor.kiev.ua/wot/images/arrow/lb_rt8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column6 row9"><a href="tank/VK2801" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-vk2801.png"></div><span class="mark" title="VK 28.01">VK 28.01</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column6 row10"><a href="tank/PzIV_schmalturm" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-pziv_schmalturm.png"></div><span class="mark" title="Pz.Kpfw. IV Schmalturm">Pz. IV S.</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="3750" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column7 row1"><a href="tank/G_Panther" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-g_panther.png"></div><span class="mark" title="G.W. Panther">G.W. Panther</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column7 row2"><a href="tank/Sturer_Emil" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-sturer_emil.png"></div><span class="mark" title="Sturer Emil">St. Emil</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:196;">75 боёв<br/>41 побед<br/>54,67 %</div><div class="gamerbattles" style="z-index:197;">75</div></div>
<div class="tblock column7 row3"><a href="tank/JagdPanther" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-jagdpanther.png"></div><span class="mark" title="Jagdpanther">JPanther</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column7 row4"><a href="tank/E-25" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-e-25.png"></div><span class="mark" title="E 25">E 25</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="6700" width="12" height="12"></span><span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class3.png" alt=""></span><div class="gamerstats" style="z-index:192;">111 боёв<br/>58 побед<br/>52,25 %</div><div class="gamerbattles" style="z-index:193;">111</div></div>
<div class="tblock column7 row5"><a href="tank/PzVI_Tiger_P" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-pzvi_tiger_p.png"></div><span class="mark" title="Tiger (P)">Tiger (P)</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="lineD" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column7 row6"><a href="tank/PzVI" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-pzvi.png"></div><span class="mark" title="Tiger I">Tiger I</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="arrTB" src="http://armor.kiev.ua/wot/images/arrow/t_b8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:188;">91 боёв<br/>62 побед<br/>68,13 %</div><div class="gamerbattles" style="z-index:189;">91</div></div>
<div class="tblock column7 row8"><a href="tank/VK3002DB" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-vk3002db.png"></div><span class="mark" title="VK 30.02 (D)">VK 30.02 D</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column7 row7"><a href="tank/PzV" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-pzv.png"></div><span class="mark" title="Panther">Panther</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column7 row9"><a href="tank/Auf_Panther" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-auf_panther.png"></div><span class="mark" title="Aufklärungspanzer Panther">Aufkl.Panther</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column8 row9"><a href="tank/G103_RU_251" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-g103_ru_251.png"></div><span class="mark" title="Spähpanzer Ru 251">Ru 251</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column7 row10"><a href="tank/Panther_M10" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-panther_m10.png"></div><span class="mark" title="Panther/M10">Panther/M10</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="5750" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column8 row1"><a href="tank/GW_Tiger_P" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-gw_tiger_p.png"></div><span class="mark" title="G.W. Tiger (P)">G.W. Tiger P</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column8 row2"><a href="tank/RhB_Waffentrager" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-rhb_waffentrager.png"></div><span class="mark" title="Rhm.-Borsig Waffenträger">Rhm.-B. WT</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column8 row3"><a href="tank/JagdPantherII" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-jagdpantherii.png"></div><span class="mark" title="Jagdpanther II">JPanther II</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column8 row4"><a href="tank/Ferdinand" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-ferdinand.png"></div><span class="mark" title="Ferdinand">Ferdinand</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLRD" src="http://armor.kiev.ua/wot/images/arrow/lt_rb8.png" alt="">
<img class="arrLRU" src="http://armor.kiev.ua/wot/images/arrow/lb_rt8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column8 row5"><a href="tank/VK4502A" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-vk4502a.png"></div><span class="mark" title="VK 45.02 (P) Ausf. A">VK 45.02 A</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column8 row6"><a href="tank/PzVIB_Tiger_II" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-pzvib_tiger_ii.png"></div><span class="mark" title="Tiger II">Tiger II</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="arrLRU" src="http://armor.kiev.ua/wot/images/arrow/lb_rt8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column8 row8"><a href="tank/Indien_Panzer" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-indien_panzer.png"></div><span class="mark" title="Indien-Panzer">Indien-Pz.</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="arrLRU" src="http://armor.kiev.ua/wot/images/arrow/lb_rt8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column8 row7"><a href="tank/Panther_II" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-panther_ii.png"></div><span class="mark" title="Panther II">Panther II</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column8 row11"><a href="tank/JagdTiger_SdKfz_185" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-jagdtiger_sdkfz_185.png"></div><span class="mark" title="8,8 cm Pak 43 Jagdtiger">JgTig.8,8 cm</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="10000" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column8 row10"><a href="tank/Lowe" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-lowe.png"></div><span class="mark" title="Löwe">Löwe</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="12500" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column9 row1"><a href="tank/G_Tiger" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-g_tiger.png"></div><span class="mark" title="G.W. Tiger">G.W. Tiger</span><span class="level">IX</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column9 row2"><a href="tank/Waffentrager_IV" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-waffentrager_iv.png"></div><span class="mark" title="Waffenträger auf Pz. IV">WT auf Pz. IV</span><span class="level">IX</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column9 row3"><a href="tank/JagdTiger" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-jagdtiger.png"></div><span class="mark" title="Jagdtiger">Jagdtiger</span><span class="level">IX</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column9 row5"><a href="tank/VK4502P" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-vk4502p.png"></div><span class="mark" title="VK 45.02 (P) Ausf. B">VK 45.02 B</span><span class="level">IX</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column9 row6"><a href="tank/E-75" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-e-75.png"></div><span class="mark" title="E 75">E 75</span><span class="level">IX</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column9 row7"><a href="tank/E-50" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-e-50.png"></div><span class="mark" title="E 50">E 50</span><span class="level">IX</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column9 row8"><a href="tank/Pro_Ag_A" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-pro_ag_a.png"></div><span class="mark" title="Leopard Prototyp A">Leopard PT A</span><span class="level">IX</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column10 row1"><a href="tank/G_E" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-g_e.png"></div><span class="mark" title="G.W. E 100">G.W. E 100</span><span class="level">X</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column10 row2"><a href="tank/Waffentrager_E100" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-waffentrager_e100.png"></div><span class="mark" title="Waffenträger auf E 100">WT auf E 100</span><span class="level">X</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column10 row3"><a href="tank/JagdPz_E100" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-jagdpz_e100.png"></div><span class="mark" title="Jagdpanzer E 100">Jg.Pz. E 100</span><span class="level">X</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column10 row5"><a href="tank/Maus" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-maus.png"></div><span class="mark" title="Maus">Maus</span><span class="level">X</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column10 row6"><a href="tank/E-100" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-e-100.png"></div><span class="mark" title="E 100">E 100</span><span class="level">X</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column10 row7"><a href="tank/E50_Ausf_M" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-e50_ausf_m.png"></div><span class="mark" title="E 50 Ausf. M">E 50 M</span><span class="level">X</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column10 row8"><a href="tank/Leopard1" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/germany-leopard1.png"></div><span class="mark" title="Leopard 1">Leopard 1</span><span class="level">X</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
</div>
</div>
</div>