    <div class="nationTree" id="ntree-uk" style="display: none;">
    <div class="treeWrapper"><div class="levelLine" style="left:0px;"></div>
    <div class="levelLine" style="left:324px;"></div>
    <div class="levelLine" style="left:648px;"></div>
    <div class="levelLine" style="left:972px;"></div>
    <div class="levelLine" style="left:1296px;"></div>
    <div id="levels"><div>I</div>
    <div>II</div>
    <div>III</div>
    <div>IV</div>
    <div>V</div>
    <div>VI</div>
    <div>VII</div>
    <div>VIII</div>
    <div>IX</div>
    <div>X</div>
    </div>
    <div id="tree">
    <div class="tblock column1 row5"><a href="tank/GB01_Medium_Mark_I" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb01_medium_mark_i.png"></div><span class="mark" title="Vickers Medium Mk. I">Medium I</span><span class="level">I</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <img class="lineRD" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <img class="lineRD" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="162" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <img class="lineRU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="108" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <img class="lineRU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <img class="lineRD" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="216" alt="">
    <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class1.png" alt=""></span><div class="gamerstats" style="z-index:190;">4 боёв<br/>3 побед<br/>75,00 %</div><div class="gamerbattles" style="z-index:191;">4</div></div>
    <div class="tblock column2 row3"><a href="tank/GB58_Cruiser_Mk_III" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb58_cruiser_mk_iii.png"></div><span class="mark" title="Cruiser Mk. III">Cruiser III</span><span class="level">II</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column2 row4"><a href="tank/GB39_Universal_CarrierQF2" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb39_universal_carrierqf2.png"></div><span class="mark" title="Universal Carrier 2-pdr">UC 2-pdr</span><span class="level">II</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class3.png" alt=""></span><div class="gamerstats" style="z-index:192;">7 боёв<br/>6 побед<br/>85,71 %</div><div class="gamerbattles" style="z-index:193;">7</div></div>
    <div class="tblock column2 row6"><a href="tank/GB05_Vickers_Medium_Mk_II" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb05_vickers_medium_mk_ii.png"></div><span class="mark" title="Vickers Medium Mk. II">Medium II</span><span class="level">II</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class2.png" alt=""></span><div class="gamerstats" style="z-index:188;">9 боёв<br/>2 побед<br/>22,22 %</div><div class="gamerbattles" style="z-index:189;">9</div></div>
    <div class="tblock column2 row8"><a href="tank/GB03_Cruiser_Mk_I" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb03_cruiser_mk_i.png"></div><span class="mark" title="Cruiser Mk. I">Cruiser I</span><span class="level">II</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column2 row9"><a href="tank/GB25_Loyd_Carrier" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb25_loyd_carrier.png"></div><span class="mark" title="Loyd Gun Carriage">Loyd GC</span><span class="level">II</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class3.png" alt=""></span><div class="gamerstats" style="z-index:182;">9 боёв<br/>5 побед<br/>55,56 %</div><div class="gamerbattles" style="z-index:183;">9</div></div>
    <div class="tblock column2 row10"><a href="tank/GB76_Mk_VIC" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb76_mk_vic.png"></div><span class="mark" title="Light Mk. VIC">Light VIC</span><span class="level">II</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="750" width="12" height="12"></span><div class="gamerstats" style="z-index:180;">1 боёв<br/>1 побед<br/>100,00 %</div><div class="gamerbattles" style="z-index:181;">1</div></div>
    <div class="tblock column3 row3"><a href="tank/GB59_Cruiser_Mk_IV" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb59_cruiser_mk_iv.png"></div><span class="mark" title="Cruiser Mk. IV">Cruiser IV</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column3 row4"><a href="tank/GB42_Valentine_AT" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb42_valentine_at.png"></div><span class="mark" title="Valentine AT">Valentine AT</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column3 row6"><a href="tank/GB06_Vickers_Medium_Mk_III" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb06_vickers_medium_mk_iii.png"></div><span class="mark" title="Vickers Medium Mk. III">Medium III</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class2.png" alt=""></span><div class="gamerstats" style="z-index:188;">10 боёв<br/>6 побед<br/>60,00 %</div><div class="gamerbattles" style="z-index:189;">10</div></div>
    <div class="tblock column3 row8"><a href="tank/GB69_Cruiser_Mk_II" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb69_cruiser_mk_ii.png"></div><span class="mark" title="Cruiser Mk. II">Cruiser II</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column3 row9"><a href="tank/GB27_Sexton" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb27_sexton.png"></div><span class="mark" title="Sexton II">Sexton II</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class2.png" alt=""></span><div class="gamerstats" style="z-index:182;">13 боёв<br/>7 побед<br/>53,85 %</div><div class="gamerbattles" style="z-index:183;">13</div></div>
    <div class="tblock column3 row10"><a href="tank/GB78_Sexton_I" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb78_sexton_i.png"></div><span class="mark" title="Sexton I">Sexton I</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="1250" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column4 row3"><a href="tank/GB60_Covenanter" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb60_covenanter.png"></div><span class="mark" title="Covenanter">Covenanter</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column4 row4"><a href="tank/GB57_Alecto" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb57_alecto.png"></div><span class="mark" title="Alecto">Alecto</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column4 row6"><a href="tank/GB07_Matilda" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb07_matilda.png"></div><span class="mark" title="Matilda">Matilda</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:188;">65 боёв<br/>37 побед<br/>56,92 %</div><div class="gamerbattles" style="z-index:189;">65</div></div>
    <div class="tblock column4 row8"><a href="tank/GB04_Valentine" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb04_valentine.png"></div><span class="mark" title="Valentine">Valentine</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column5 row8"><a href="tank/GB44_Archer" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb44_archer.png"></div><span class="mark" title="Archer">Archer</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column6 row8"><a href="tank/GB45_Achilles_IIC" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb45_achilles_iic.png"></div><span class="mark" title="Achilles">Achilles</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column7 row8"><a href="tank/GB41_Challenger" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb41_challenger.png"></div><span class="mark" title="Challenger">Challenger</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column8 row8"><a href="tank/GB80_Charioteer" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb80_charioteer.png"></div><span class="mark" title="Charioteer">Charioteer</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column9 row8"><a href="tank/GB81_FV4004" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb81_fv4004.png"></div><span class="mark" title="FV4004 Conway">Conway</span><span class="level">IX</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column10 row8"><a href="tank/GB83_FV4005" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb83_fv4005.png"></div><span class="mark" title="FV4005 Stage II">FV4005</span><span class="level">X</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column2 row7"><a href="tank/GB14_M2" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb14_m2.png"></div><span class="mark" title="M2">M2</span><span class="level">II</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column3 row7"><a href="tank/GB15_Stuart_I" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb15_stuart_i.png"></div><span class="mark" title="Stuart I-IV">Stuart I-IV</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column4 row7"><a href="tank/GB17_Grant_I" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb17_grant_i.png"></div><span class="mark" title="Grant">Grant</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column5 row7"><a href="tank/GB50_Sherman_III" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb50_sherman_iii.png"></div><span class="mark" title="Sherman III">Sherman III</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column6 row7"><a href="tank/GB19_Sherman_Firefly" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb19_sherman_firefly.png"></div><span class="mark" title="Sherman Firefly">Firefly</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <img class="lineRD" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column4 row9"><a href="tank/GB26_Birch_Gun" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb26_birch_gun.png"></div><span class="mark" title="Birch Gun">Birch Gun</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class3.png" alt=""></span><div class="gamerstats" style="z-index:182;">28 боёв<br/>20 побед<br/>71,43 %</div><div class="gamerbattles" style="z-index:183;">28</div></div>
    <div class="tblock column5 row3"><a href="tank/GB20_Crusader" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb20_crusader.png"></div><span class="mark" title="Crusader">Crusader</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column5 row4"><a href="tank/GB73_AT2" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb73_at2.png"></div><span class="mark" title="AT 2">AT 2</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column5 row5"><a href="tank/GB68_Matilda_Black_Prince" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb68_matilda_black_prince.png"></div><span class="mark" title="Matilda Black Prince">Matilda BP</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="1750" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column5 row6"><a href="tank/GB08_Churchill_I" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb08_churchill_i.png"></div><span class="mark" title="Churchill I">Churchill I</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <img class="lineRU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column5 row10"><a href="tank/GB51_Excelsior" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb51_excelsior.png"></div><span class="mark" title="Excelsior">Excelsior</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="1500" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column5 row9"><a href="tank/GB28_Bishop" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb28_bishop.png"></div><span class="mark" title="Bishop">Bishop</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLRD" src="http://armor.kiev.ua/wot/images/arrow/lt_rb8.png" alt="">
    <img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column6 row3"><a href="tank/GB21_Cromwell" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb21_cromwell.png"></div><span class="mark" title="Cromwell">Cromwell</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column6 row4"><a href="tank/GB74_AT8" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb74_at8.png"></div><span class="mark" title="AT 8">AT 8</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column6 row5"><a href="tank/GB40_Gun_Carrier_Churchill" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb40_gun_carrier_churchill.png"></div><span class="mark" title="Churchill Gun Carrier">Churchill GC</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <img class="lineRU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column6 row6"><a href="tank/GB09_Churchill_VII" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb09_churchill_vii.png"></div><span class="mark" title="Churchill VII">Churchill VII</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column6 row10"><a href="tank/GB63_TOG_II" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb63_tog_ii.png"></div><span class="mark" title="TOG II*">TOG II*</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="3500" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column6 row9"><a href="tank/GB77_FV304" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb77_fv304.png"></div><span class="mark" title="FV304">FV304</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column7 row3"><a href="tank/GB22_Comet" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb22_comet.png"></div><span class="mark" title="Comet">Comet</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column7 row4"><a href="tank/GB75_AT7" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb75_at7.png"></div><span class="mark" title="AT 7">AT 7</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column7 row6"><a href="tank/GB10_Black_Prince" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb10_black_prince.png"></div><span class="mark" title="Black Prince">Black Prince</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column7 row5"><a href="tank/GB71_AT_15A" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb71_at_15a.png"></div><span class="mark" title="AT 15A">AT 15A</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="6500" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column7 row9"><a href="tank/GB29_Crusader_5inch" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb29_crusader_5inch.png"></div><span class="mark" title="Crusader 5.5-in. SP">Crusader SP</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column8 row3"><a href="tank/GB23_Centurion" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb23_centurion.png"></div><span class="mark" title="Centurion Mk. I">Centurion I</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column8 row4"><a href="tank/GB72_AT15" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb72_at15.png"></div><span class="mark" title="AT 15">AT 15</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column8 row6"><a href="tank/GB11_Caernarvon" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb11_caernarvon.png"></div><span class="mark" title="Caernarvon">Caernarvon</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column8 row9"><a href="tank/GB79_FV206" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb79_fv206.png"></div><span class="mark" title="FV207">FV207</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column9 row3"><a href="tank/GB24_Centurion_Mk3" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb24_centurion_mk3.png"></div><span class="mark" title="Centurion Mk. 7/1">Centurion 7/1</span><span class="level">IX</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column9 row4"><a href="tank/GB32_Tortoise" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb32_tortoise.png"></div><span class="mark" title="Tortoise">Tortoise</span><span class="level">IX</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column9 row6"><a href="tank/GB12_Conqueror" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb12_conqueror.png"></div><span class="mark" title="Conqueror">Conqueror</span><span class="level">IX</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column9 row9"><a href="tank/GB30_FV3805" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb30_fv3805.png"></div><span class="mark" title="FV3805">FV3805</span><span class="level">IX</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column10 row3"><a href="tank/GB70_FV4202_105" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb70_fv4202_105.png"></div><span class="mark" title="FV4202">FV4202</span><span class="level">X</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column10 row4"><a href="tank/GB48_FV215b_183" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb48_fv215b_183.png"></div><span class="mark" title="FV215b (183)">FV215b 183</span><span class="level">X</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column10 row6"><a href="tank/GB13_FV215b" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb13_fv215b.png"></div><span class="mark" title="FV215b">FV215b</span><span class="level">X</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    <div class="tblock column10 row9"><a href="tank/GB31_Conqueror_Gun" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/uk-gb31_conqueror_gun.png"></div><span class="mark" title="Conqueror Gun Carriage">ConquerorGC</span><span class="level">X</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
    <span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
    </div>
    </div>
    </div>