<div class="nationTree" id="ntree-ussr" style="display: none;">
<div class="treeWrapper"><div class="levelLine" style="left:0px;"></div>
<div class="levelLine" style="left:324px;"></div>
<div class="levelLine" style="left:648px;"></div>
<div class="levelLine" style="left:972px;"></div>
<div class="levelLine" style="left:1296px;"></div>
<div id="levels"><div>I</div>
<div>II</div>
<div>III</div>
<div>IV</div>
<div>V</div>
<div>VI</div>
<div>VII</div>
<div>VIII</div>
<div>IX</div>
<div>X</div>
</div>
  <div id="tree">
  <div class="tblock column1 row5"><a href="tank/MS-1" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-ms-1.png"></div><span class="mark" title="МС-1">МС-1</span><span class="level">I</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="162" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRD" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRD" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="270" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="108" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:190;">33 боёв<br/>23 побед<br/>69,70 %</div><div class="gamerbattles" style="z-index:191;">33</div></div>
<div class="tblock column2 row2"><a href="tank/AT-1" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-at-1.png"></div><span class="mark" title="АТ-1">АТ-1</span><span class="level">II</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class2.png" alt=""></span><div class="gamerstats" style="z-index:196;">10 боёв<br/>4 побед<br/>40,00 %</div><div class="gamerbattles" style="z-index:197;">10</div></div>
<div class="tblock column2 row3"><a href="tank/T-60" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-t-60.png"></div><span class="mark" title="Т-60">Т-60</span><span class="level">II</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column2 row4"><a href="tank/BT-2" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-bt-2.png"></div><span class="mark" title="БТ-2">БТ-2</span><span class="level">II</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class2.png" alt=""></span><div class="gamerstats" style="z-index:192;">3 боёв<br/>2 побед<br/>66,67 %</div><div class="gamerbattles" style="z-index:193;">3</div></div>
<div class="tblock column2 row5"><a href="tank/Tetrarch_LL" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-tetrarch_ll.png"></div><span class="mark" title="Тетрарх">Тетрарх</span><span class="level">II</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="750" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column2 row6"><a href="tank/T-26" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-t-26.png"></div><span class="mark" title="Т-26">Т-26</span><span class="level">II</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class2.png" alt=""></span><div class="gamerstats" style="z-index:188;">14 боёв<br/>7 побед<br/>50,00 %</div><div class="gamerbattles" style="z-index:189;">14</div></div>
<div class="tblock column2 row10"><a href="tank/SU-18" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-su-18.png"></div><span class="mark" title="СУ-18">СУ-18</span><span class="level">II</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column3 row2"><a href="tank/SU-76" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-su-76.png"></div><span class="mark" title="СУ-76">СУ-76</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="arrBT" src="http://armor.kiev.ua/wot/images/arrow/b_t8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class2.png" alt=""></span><div class="gamerstats" style="z-index:196;">17 боёв<br/>7 побед<br/>41,18 %</div><div class="gamerbattles" style="z-index:197;">17</div></div>
<div class="tblock column3 row3"><a href="tank/T-70" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-t-70.png"></div><span class="mark" title="Т-70">Т-70</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column3 row4"><a href="tank/BT-7" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-bt-7.png"></div><span class="mark" title="БТ-7">БТ-7</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:192;">18 боёв<br/>12 побед<br/>66,67 %</div><div class="gamerbattles" style="z-index:193;">18</div></div>
<div class="tblock column3 row9"><a href="tank/T-127" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-t-127.png"></div><span class="mark" title="Т-127">Т-127</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="850" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column3 row6"><a href="tank/T-46" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-t-46.png"></div><span class="mark" title="Т-46">Т-46</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRD" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="108" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:188;">217 боёв<br/>138 побед<br/>63,59 %</div><div class="gamerbattles" style="z-index:189;">217</div></div>
<div class="tblock column3 row8"><a href="tank/LTP" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-ltp.png"></div><span class="mark" title="ЛТП">ЛТП</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="850" width="12" height="12"></span><span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:184;">13 боёв<br/>5 побед<br/>38,46 %</div><div class="gamerbattles" style="z-index:185;">13</div></div>
<div class="tblock column3 row10"><a href="tank/SU-26" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-su-26.png"></div><span class="mark" title="СУ-26">СУ-26</span><span class="level">III</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column4 row2"><a href="tank/GAZ-74b" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-gaz-74b.png"></div><span class="mark" title="СУ-85Б">СУ-85Б</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column4 row3"><a href="tank/T80" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-t80.png"></div><span class="mark" title="Т-80">Т-80</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRD" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column4 row4"><a href="tank/A-20" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-a-20.png"></div><span class="mark" title="А-20">А-20</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:192;">18 боёв<br/>9 побед<br/>50,00 %</div><div class="gamerbattles" style="z-index:193;">18</div></div>
<div class="tblock column4 row9"><a href="tank/Valentine_LL" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-valentine_ll.png"></div><span class="mark" title="Валентайн II">Валентайн II</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="1000" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column4 row5"><a href="tank/T-50" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-t-50.png"></div><span class="mark" title="Т-50">Т-50</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column4 row8"><a href="tank/T-28" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-t-28.png"></div><span class="mark" title="Т-28">Т-28</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class2.png" alt=""></span><div class="gamerstats" style="z-index:184;">59 боёв<br/>28 побед<br/>47,46 %</div><div class="gamerbattles" style="z-index:185;">59</div></div>
<div class="tblock column4 row10"><a href="tank/SU-5" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-su-5.png"></div><span class="mark" title="СУ-5">СУ-5</span><span class="level">IV</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column5 row1"><a href="tank/SU_85I" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-su_85i.png"></div><span class="mark" title="СУ-85И">СУ-85И</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="2300" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column5 row2"><a href="tank/SU-85" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-su-85.png"></div><span class="mark" title="СУ-85">СУ-85</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="arrBT" src="http://armor.kiev.ua/wot/images/arrow/b_t8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class3.png" alt=""></span><div class="gamerstats" style="z-index:196;">65 боёв<br/>41 побед<br/>63,08 %</div><div class="gamerbattles" style="z-index:197;">65</div></div>
<div class="tblock column5 row4"><a href="tank/R04_T-34" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-r04_t-34.png"></div><span class="mark" title="Т-34">Т-34</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="lineU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="108" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRD" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:192;">96 боёв<br/>66 побед<br/>68,75 %</div><div class="gamerbattles" style="z-index:193;">96</div></div>
<div class="tblock column5 row5"><a href="tank/Matilda_II_LL" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-matilda_ii_ll.png"></div><span class="mark" title="Матильда IV">Матильда IV</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="1500" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column5 row8"><a href="tank/KV1" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-kv1.png"></div><span class="mark" title="КВ-1">КВ-1</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="lineU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRD" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class3.png" alt=""></span><div class="gamerstats" style="z-index:184;">228 боёв<br/>129 побед<br/>56,58 %</div><div class="gamerbattles" style="z-index:185;">228</div></div>
<div class="tblock column5 row9"><a href="tank/Churchill_LL" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-churchill_ll.png"></div><span class="mark" title="Черчилль III">Черчилль III</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="1500" width="12" height="12"></span><span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:182;">270 боёв<br/>158 побед<br/>58,52 %</div><div class="gamerbattles" style="z-index:183;">270</div></div>
<div class="tblock column5 row10"><a href="tank/SU122A" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-su122a.png"></div><span class="mark" title="СУ-122А">СУ-122А</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column6 row1"><a href="tank/SU100Y" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-su100y.png"></div><span class="mark" title="СУ-100Y">СУ-100Y</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="3250" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column6 row2"><a href="tank/SU-100" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-su-100.png"></div><span class="mark" title="СУ-100">СУ-100</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class3.png" alt=""></span><div class="gamerstats" style="z-index:196;">71 боёв<br/>46 побед<br/>64,79 %</div><div class="gamerbattles" style="z-index:197;">71</div></div>
<div class="tblock column6 row5"><a href="tank/T-34-85" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-t-34-85.png"></div><span class="mark" title="Т-34-85">Т-34-85</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:190;">58 боёв<br/>36 побед<br/>62,07 %</div><div class="gamerbattles" style="z-index:191;">58</div></div>
<div class="tblock column6 row3"><a href="tank/A43" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-a43.png"></div><span class="mark" title="А-43">А-43</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column6 row4"><a href="tank/MT25" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-mt25.png"></div><span class="mark" title="МТ-25">МТ-25</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column7 row4"><a href="tank/R107_LTB" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-r107_ltb.png"></div><span class="mark" title="ЛТТБ">ЛТТБ</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column8 row4"><a href="tank/R109_T54S" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-r109_t54s.png"></div><span class="mark" title="Т-54 облегчённый">Т-54 обл.</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-lightTank.png" align="top" alt="Лёгкий танк" title="Лёгкий танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column5 row7"><a href="tank/KV-1s" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-kv-1s.png"></div><span class="mark" title="КВ-1С">КВ-1С</span><span class="level">V</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrBT" src="http://armor.kiev.ua/wot/images/arrow/b_t8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class3.png" alt=""></span><div class="gamerstats" style="z-index:186;">11 боёв<br/>11 побед<br/>100,00 %</div><div class="gamerbattles" style="z-index:187;">11</div></div>
<div class="tblock column6 row7"><a href="tank/R106_KV85" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-r106_kv85.png"></div><span class="mark" title="КВ-85">КВ-85</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:186;">728 боёв<br/>430 побед<br/>59,07 %</div><div class="gamerbattles" style="z-index:187;">728</div></div>
<div class="tblock column6 row8"><a href="tank/T150" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-t150.png"></div><span class="mark" title="Т-150">Т-150</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="arrBT" src="http://armor.kiev.ua/wot/images/arrow/b_t8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column6 row9"><a href="tank/KV2" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-kv2.png"></div><span class="mark" title="КВ-2">КВ-2</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:182;">26 боёв<br/>18 побед<br/>69,23 %</div><div class="gamerbattles" style="z-index:183;">26</div></div>
<div class="tblock column6 row10"><a href="tank/SU-8" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-su-8.png"></div><span class="mark" title="СУ-8">СУ-8</span><span class="level">VI</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column7 row1"><a href="tank/SU-152" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-su-152.png"></div><span class="mark" title="СУ-152">СУ-152</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class1.png" alt=""></span><div class="gamerstats" style="z-index:198;">6 боёв<br/>4 побед<br/>66,67 %</div><div class="gamerbattles" style="z-index:199;">6</div></div>
<div class="tblock column7 row2"><a href="tank/SU100M1" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-su100m1.png"></div><span class="mark" title="СУ-100М1">СУ-100М1</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column7 row11"><a href="tank/SU122_44" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-su122_44.png"></div><span class="mark" title="СУ-122-44">СУ-122-44</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="6750" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column7 row5"><a href="tank/T-43" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-t-43.png"></div><span class="mark" title="Т-43">Т-43</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="arrBT" src="http://armor.kiev.ua/wot/images/arrow/b_t8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:190;">114 боёв<br/>80 побед<br/>70,18 %</div><div class="gamerbattles" style="z-index:191;">114</div></div>
<div class="tblock column7 row6"><a href="tank/KV-13" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-kv-13.png"></div><span class="mark" title="КВ-13">КВ-13</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLRD" src="http://armor.kiev.ua/wot/images/arrow/lt_rb8.png" alt="">
<img class="arrLRU" src="http://armor.kiev.ua/wot/images/arrow/lb_rt8.png" alt="">
<img class="lineU" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<img class="lineD" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column7 row3"><a href="tank/A44" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-a44.png"></div><span class="mark" title="А-44">А-44</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column7 row7"><a href="tank/IS" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-is.png"></div><span class="mark" title="ИС">ИС</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="arrTB" src="http://armor.kiev.ua/wot/images/arrow/t_b8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:186;">228 боёв<br/>151 побед<br/>66,23 %</div><div class="gamerbattles" style="z-index:187;">228</div></div>
<div class="tblock column7 row8"><a href="tank/KV-3" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-kv-3.png"></div><span class="mark" title="КВ-3">КВ-3</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column7 row9"><a href="tank/S-51" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-s-51.png"></div><span class="mark" title="С-51">С-51</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRD" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column7 row10"><a href="tank/SU14_1" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-su14_1.png"></div><span class="mark" title="СУ-14-1">СУ-14-1</span><span class="level">VII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column8 row1"><a href="tank/ISU-152" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-isu-152.png"></div><span class="mark" title="ИСУ-152">ИСУ-152</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column8 row2"><a href="tank/SU-101" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-su-101.png"></div><span class="mark" title="СУ-101">СУ-101</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column8 row3"><a href="tank/Object416" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-object416.png"></div><span class="mark" title="Объект 416">Об. 416</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column8 row5"><a href="tank/T-44" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-t-44.png"></div><span class="mark" title="Т-44">Т-44</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column8 row11"><a href="tank/Object252" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-object252.png"></div><span class="mark" title="ИС-6">ИС-6</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="11800" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column8 row7"><a href="tank/IS-3" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-is-3.png"></div><span class="mark" title="ИС-3">ИС-3</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:186;">510 боёв<br/>288 побед<br/>56,47 %</div><div class="gamerbattles" style="z-index:187;">510</div></div>
<div class="tblock column8 row8"><a href="tank/KV4" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-kv4.png"></div><span class="mark" title="КВ-4">КВ-4</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column8 row9"><a href="tank/KV-5" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-kv-5.png"></div><span class="mark" title="КВ-5">КВ-5</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><span class="golden"><img src="http://armor.kiev.ua/wot/images/gold.png" title="7500" width="12" height="12"></span><span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column8 row10"><a href="tank/SU-14" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-su-14.png"></div><span class="mark" title="СУ-14-2">СУ-14-2</span><span class="level">VIII</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column9 row1"><a href="tank/Object_704" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-object_704.png"></div><span class="mark" title="Об. 704">Об. 704</span><span class="level">IX</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column9 row2"><a href="tank/SU122_54" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-su122_54.png"></div><span class="mark" title="СУ-122-54">СУ-122-54</span><span class="level">IX</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column9 row3"><a href="tank/R104_Object_430_II" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-r104_object_430_ii.png"></div><span class="mark" title="Объект 430 Вариант II">Об. 430 II</span><span class="level">IX</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column9 row4"><a href="tank/T-54" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-t-54.png"></div><span class="mark" title="Т-54">Т-54</span><span class="level">IX</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="arrLRD" src="http://armor.kiev.ua/wot/images/arrow/lt_rb8.png" alt="">
<img class="arrLRU" src="http://armor.kiev.ua/wot/images/arrow/lb_rt8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<img class="lineRD" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="1" height="54" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column9 row7"><a href="tank/IS8" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-is8.png"></div><span class="mark" title="ИС-8">ИС-8</span><span class="level">IX</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span class="mastery"><img src="http://armor.kiev.ua/wot/images/awards/class4.png" alt=""></span><div class="gamerstats" style="z-index:186;">132 боёв<br/>86 побед<br/>65,15 %</div><div class="gamerbattles" style="z-index:187;">132</div></div>
<div class="tblock column9 row8"><a href="tank/ST_I" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-st_i.png"></div><span class="mark" title="СТ-I">СТ-I</span><span class="level">IX</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column9 row10"><a href="tank/Object_212" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-object_212.png"></div><span class="mark" title="212А">212А</span><span class="level">IX</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<img class="line2R" src="http://armor.kiev.ua/wot/images/arrow/point8.png" width="81" height="1" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column10 row1"><a href="tank/Object268" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-object268.png"></div><span class="mark" title="Объект 268">Об. 268</span><span class="level">X</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column10 row2"><a href="tank/Object263" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-object263.png"></div><span class="mark" title="Объект 263">Об. 263</span><span class="level">X</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-AT-SPG.png" align="top" alt="ПТ САУ" title="ПТ САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column10 row3"><a href="tank/Object_430" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-object_430.png"></div><span class="mark" title="Объект 430">Об. 430</span><span class="level">X</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column10 row4"><a href="tank/T62A" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-t62a.png"></div><span class="mark" title="Т-62А">Т-62А</span><span class="level">X</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column10 row5"><a href="tank/Object_140" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-object_140.png"></div><span class="mark" title="Объект 140">Об. 140</span><span class="level">X</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-mediumTank.png" align="top" alt="Средний танк" title="Средний танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column10 row7"><a href="tank/IS-7" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-is-7.png"></div><span class="mark" title="ИС-7">ИС-7</span><span class="level">X</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column10 row8"><a href="tank/IS-4" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-is-4.png"></div><span class="mark" title="ИС-4">ИС-4</span><span class="level">X</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-heavyTank.png" align="top" alt="Тяжёлый танк" title="Тяжёлый танк"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
<div class="tblock column10 row10"><a href="tank/Object_261" target="_top"><div class="vicLogo"><img src="http://armor.kiev.ua/wot/images/vehicles/s/ussr-object_261.png"></div><span class="mark" title="Объект 261">Об. 261</span><span class="level">X</span><span class="class"><img src="http://armor.kiev.ua/wot/images/type-SPG.png" align="top" alt="САУ" title="САУ"></span></a><img class="arrLR" src="http://armor.kiev.ua/wot/images/arrow/l_r8.png" alt="">
<span style="position: absolute; width: 100%; height: 100%; top: 0px; background-color: rgba(0, 0, 0, 0.5);"></span></div>
</div>
</div>
</div>